In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [34]:
df = pd.read_csv("Event_Data.csv")

In [35]:
df.head()

,Event_ID,Event_Name,Organizer Name,Description,Venue,Date,Time,Attendance,Feedback_Score
0,1,Criminal Crew Dance,CRIMINAL,"Lorem ipsum dolor sit amet, consectetuer adipi...",Main Ground,8/2/2022,9:12 PM,606,5
1,2,SI Crew Dance,SI,Vestibulum ac est lacinia nisi venenatis trist...,ECE Building,3/8/2022,8:26 PM,353,2
2,3,Paryash,TTA,Fusce consequat. Nulla nisl. Nunc nisl.\n\nDui...,MBH Ground,11/30/2022,6:33 PM,362,5
3,4,Team Culture Affairs,SI,Pellentesque at nulla. Suspendisse potenti. Cr...,CSH,5/17/2022,7:15 PM,511,5
4,5,Umang,ZEAL,"Sed sagittis. Nam congue, risus semper porta v...",IT Building,7/19/2023,11:00 AM,590,4

In [41]:
df = pd.DataFrame(data)

# Feature Selection
X = df[['Event_ID', 'Attendance', 'Feedback_Score']]

# Target variables
y_attendance = df['Attendance']
y_feedback = df['Feedback_Score']

# Split the data into training and testing sets for attendance prediction
X_train_attendance, X_test_attendance, y_train_attendance, y_test_attendance = train_test_split(X, y_attendance, test_size=0.2, random_state=42)

# Split the data into training and testing sets for feedback prediction
X_train_feedback, X_test_feedback, y_train_feedback, y_test_feedback = train_test_split(X, y_feedback, test_size=0.2, random_state=42)

# Model Selection and Training for attendance prediction
reg_attendance = RandomForestRegressor()
reg_attendance.fit(X_train_attendance, y_train_attendance)

# Model Evaluation for attendance prediction
y_pred_attendance = reg_attendance.predict(X_test_attendance)
mse_attendance = mean_squared_error(y_test_attendance, y_pred_attendance)
print("Mean Squared Error for Attendance Prediction:", mse_attendance)

Mean Squared Error for Attendance Prediction: 0.5612000000000011

In [37]:
X.head()

             Event_Name  Attendance  Feedback_Score
0   Criminal Crew Dance         606               5
1         SI Crew Dance         353               2
2               Paryash         362               5
3  Team Culture Affairs         511               5
4                 Umang         590               4